# Generated by Django 2.2.5 on 2019-12-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Location', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EventName', models.CharField(max_length=20)),
                ('EventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoApp.Event')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoApp.User')),
            ],
        ),
    ]
