# Generated by Django 3.0.1 on 2019-12-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=20)),
                ('Role', models.CharField(max_length=20)),
            ],
        ),
    ]
