# Generated by Django 3.0.1 on 2019-12-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
