# Generated by Django 2.2.5 on 2019-12-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngoApp', '0002_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='EventName',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='Name',
        ),
    ]
