# Generated by Django 3.0.1 on 2019-12-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoApp', '0002_auto_20191221_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('EventName', models.CharField(max_length=20)),
                ('UserID', models.IntegerField()),
                ('EventID', models.IntegerField()),
            ],
        ),
    ]
