# Generated by Django 3.0.1 on 2019-12-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoApp', '0004_auto_20191221_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
                ('Location', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
