# Generated by Django 2.2.7 on 2019-12-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngoApp', '0009_auto_20191223_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateField(),
        ),
    ]
