# Generated by Django 2.2.7 on 2019-12-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngoApp', '0010_auto_20191223_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='EventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoApp.Event'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ngoApp.User'),
        ),
    ]
